export DDB_ENDPOINT=https://YOUR_DOCUMENT_DB_INSTANCE.documents.azure.com:443/
export DDB_AUTHKEY=YOUR_AUTH_KEY_FOR_DOCUMENT_DB
export DDB_DB_ID=expensetrackerdb
export DDB_DB_COLLECTION_ID=expensetrackercollection
export DDB_DB_COLLECTION_CAT_ID=categorycollection
